export const REPORT_DENYLIST = Object.freeze({
  severity: Object.freeze([
    'critical',
    'criticality',
    'severe',
    'severity',
    'serious',
    'urgent',
    'urgency',
    'emergency',
    'catastrophic',
    'dangerous',
    'exploitable',
    'showstopper',
    'show-stopper',
    'high priority',
    'high-priority',
    'low priority',
    'low-priority',
    'major issue',
    'minor issue',
    'major bug',
    'minor bug',
    'P0',
    'P1',
    'P2',
    'P3',
    'P4',
    'sev0',
    'sev1',
    'sev2',
    'sev3',
    'sev4',
    'sev-0',
    'sev-1',
    'sev-2',
    'sev-3',
    'sev-4',
    'CVSS',
  ]),
  authorship: Object.freeze([
    'AI-generated',
    'AI generated',
    'AI-assisted',
    'AI assisted',
    'AI-written',
    'generated by AI',
    'written by AI',
    'LLM-generated',
    'machine-generated',
    'bot-generated',
    'ChatGPT',
    'human-written',
    'written by',
    'authored by',
    'the author',
    "author's",
    'first-time contributor',
    'first-time',
    'new contributor',
    'newcomer',
    'account age',
    'drive-by',
    'low-effort',
    'low effort',
    'low-quality',
    'low quality',
    'spam',
    'slop',
    'lazy',
    'careless',
    'sloppy',
  ]),
  praise: Object.freeze([
    'great',
    'excellent',
    'awesome',
    'amazing',
    'impressive',
    'perfect',
    'wonderful',
    'fantastic',
    'brilliant',
    'outstanding',
    'superb',
    'nice',
    'good job',
    'good work',
    'well done',
    'kudos',
    'congratulations',
    'congrats',
    'thank you',
    'thanks',
    'appreciate',
    'appreciated',
    'love',
    'beautiful',
    'elegant',
    'unfortunately',
    'sorry',
    'apologies',
    'happy to',
    'glad',
    'excited',
    'please',
  ]),
});

const ALL_PHRASES: readonly string[] = [...REPORT_DENYLIST.severity, ...REPORT_DENYLIST.authorship, ...REPORT_DENYLIST.praise];

function escapeRegExp(phrase: string): string {
  return phrase.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function buildPhrasePattern(phrase: string): RegExp {
  const escaped = escapeRegExp(phrase).replace(/ /g, '\\s+');
  return new RegExp(`(?<![\\p{L}\\p{N}_])${escaped}(?![\\p{L}\\p{N}_])`, 'iu');
}

const PHRASE_PATTERNS: readonly { phrase: string; pattern: RegExp }[] = ALL_PHRASES.map((phrase) => ({
  phrase,
  pattern: buildPhrasePattern(phrase),
}));

export function reportDenylistMatches(text: string): readonly string[] {
  const matches: string[] = [];
  for (const { phrase, pattern } of PHRASE_PATTERNS) {
    if (pattern.test(text)) {
      matches.push(phrase);
    }
  }
  return matches;
}

export function maskCodeSpans(markdown: string): string {
  let result = '';
  let i = 0;
  const len = markdown.length;
  while (i < len) {
    const ch = markdown[i];
    if (ch === '`') {
      let runLength = 0;
      let j = i;
      while (j < len && markdown[j] === '`') {
        runLength++;
        j++;
      }
      const closerIndex = findCloser(markdown, j, runLength);
      if (closerIndex === -1) {
        result += markdown.slice(i, j);
        i = j;
      } else {
        result += ' ';
        i = closerIndex + runLength;
      }
    } else {
      result += ch;
      i++;
    }
  }
  return result;
}

function findCloser(markdown: string, from: number, runLength: number): number {
  const len = markdown.length;
  let i = from;
  while (i < len) {
    if (markdown[i] === '`') {
      let count = 0;
      const start = i;
      while (i < len && markdown[i] === '`') {
        count++;
        i++;
      }
      if (count === runLength) {
        return start;
      }
    } else {
      i++;
    }
  }
  return -1;
}
